### ISSUE TITLE
171015 build

### ISSUE THREAD

**Issue by adeich44** [kantjer/MagiskFiles#1]
установлен без ошибок, но safetynet не передает 
is installed without errors, but the safetynet does not pass
logs
[_magisk_debug.log](https://github.com/kantjer/MagiskFiles/files/1388502/_magisk_debug.log)
[_magisk.log](https://github.com/kantjer/MagiskFiles/files/1388503/_magisk.log)
[log.zip](https://github.com/kantjer/MagiskFiles/files/1388504/log.zip)

**Comment by CHEF-KOCH** [comment]
Can be closed.

**Comment by sjayminsgithub** [comment]
A good place for such discussions / issues is Magisk General support thread
